/** @file     Rte_EngineECU.c
  *
  * @brief    RTE Sample SWC implementation skeleton file
  *
  * @note     Generated by ETAS GmbH  RTA-RTE v5.4.1  (R4.0 backend version: v7.1.31 (Build 33134))
  *           at Tue Dec 16 20:46:28 2014
  */

#include "Rte_EngineECU.h"  //기본 header

#include "OutFuelCutDevice.h" // FuelCut  동작 device

//이하 input받을 센서 디바이스 
#include "AccelerateDevice.h"
#include "BrakeDevice.h"
#include "CoolantTemperatureDevice.h"
#include "CrankshaftPositionDevice.h"
#include "GearDevice.h"
#include "GyroDevice.h"
#include "VehicleSpeedDevice.h"

/* --------------------------------------------------------------------------- */
/* RTE Event: /SoftwarePkg/SoftwareComponentPkg/EngineECU/IB_EngineECU/OIE_SetFuelCutState */

FUNC(void, EngineECU_CODE) SetFuelCutState(CONST(Rte_SelfType_EngineECU, AUTOMATIC) self,
                                           VAR(uint8, AUTOMATIC) fuelCutState)
{
   /* ... */
   // 이거 나중에 지울거 Writen Local Variable 필요없을듯
   // Rte_IrvWrite_RE_SetFuelCutState_eX_FuelCutState(self, fuelCutState);
   // 이렇게 하면
   
   writeFuelCutDevice(fuelCutState);
   
}

/* --------------------------------------------------------------------------- */
/* RTE Event: /SoftwarePkg/SoftwareComponentPkg/EngineECU/IB_EngineECU/TE_SendData */

FUNC(void, EngineECU_CODE) SendData(CONST(Rte_SelfType_EngineECU, AUTOMATIC) self)
{
   /* ... */
   uint8 accelerateLevel=readEngine_AccelerateSensorDevice();
   uint8 brakeLevel=readEngine_BrakeSensorDevice();
   uint8 gearLevel=readEngine_GearSensorDevice();
   float32 coolantTemperatureRaw=readEngine_CoolantTemperatureDevice();
   float32 gyroRaw=readEngine_GyroSensorDevice();
   float32 crankshaftPositionRaw=readEngine_CrankshaftPositionSensorDevice();
   float32 vehicleSpeedRaw=readEngine_VehicleSpeedSensorDevice();
   
   Rte_Call_RPortAccelerate_SetAccelerateLevel( self, accelerateLevel );
   Rte_Call_RPortBrake_SetBrakeLevel( self, brakeLevel );
   Rte_Call_RPortGear_SetGearLevel( self, gearLevel );
   Rte_Call_RPortCTRAW_SetCoolantTemperatureRaw( self, coolantTemperatureRaw );
   Rte_Call_RPortGyroRAW_SetGyroRaw( self, gyroRaw );
   Rte_Call_RPortCPRAW_SetCrankshaftPositionRaw( self, crankshaftPositionRaw );
   Rte_Call_RPortVSRAW_SetVehicleSpeedRaw( self, vehicleSpeedRaw );
   
   
}

