/** @file     Rte_FuelCutAlgo.c
  *
  * @brief    RTE Sample SWC implementation skeleton file
  *
  * @note     Generated by ETAS GmbH  RTA-RTE v5.4.1  (R4.0 backend version: v7.1.31 (Build 33134))
  *           at Tue Dec 16 20:46:28 2014
  */

#include "Rte_FuelCutAlgo.h"

/* --------------------------------------------------------------------------- */
/* RTE Event: /SoftwarePkg/SoftwareComponentPkg/FuelCutAlgo/IB_FuelCutAlgo/DRE_CoolantTempertaturePls */

FUNC(void, FuelCutAlgo_CODE) SetCoolantTemperature(CONST(Rte_SelfType_FuelCutAlgo, AUTOMATIC) self)
{
   /* ... */
   float32 temperature = Rte_IRead_RE_SetCoolantTemperature_RPortCTPLS_coolantTemperature_pls( self );
   Rte_IrvWrite_RE_SetCoolantTemperature_eX_CoolantTemperature(self, temperature);
   
}

/* --------------------------------------------------------------------------- */
/* RTE Event: /SoftwarePkg/SoftwareComponentPkg/FuelCutAlgo/IB_FuelCutAlgo/DRE_CrankshaftPositionPls */

FUNC(void, FuelCutAlgo_CODE) SetCrankshaftPosition(CONST(Rte_SelfType_FuelCutAlgo, AUTOMATIC) self)
{
   /* ... */
   float32 rpm = Rte_IRead_RE_SetCrankshaftPosition_RPortCPPLS_crankshaftPosition_pls( self );
   Rte_IrvWrite_RE_SetCrankshaftPosition_eX_CrankshaftPosition(self, rpm);
}

/* --------------------------------------------------------------------------- */
/* RTE Event: /SoftwarePkg/SoftwareComponentPkg/FuelCutAlgo/IB_FuelCutAlgo/DRE_GyroPls */

FUNC(void, FuelCutAlgo_CODE) SetGyro(CONST(Rte_SelfType_FuelCutAlgo, AUTOMATIC) self)
{
   /* ... */
   float32 slope = Rte_IRead_RE_SetGyro_RPortGyroPLS_gyro_pls( self );
   Rte_IrvWrite_RE_SetGyro_eX_Gyro(self, slope);
}

/* --------------------------------------------------------------------------- */
/* RTE Event: /SoftwarePkg/SoftwareComponentPkg/FuelCutAlgo/IB_FuelCutAlgo/DRE_VehicleSpeedPls */

FUNC(void, FuelCutAlgo_CODE) SetVehicleSpeed(CONST(Rte_SelfType_FuelCutAlgo, AUTOMATIC) self)
{
   /* ... */
   float32 speed = Rte_IRead_RE_SetVehicleSpeed_RPortVSPLS_vehicleSpeed_pls( self );
   Rte_IrvWrite_RE_SetVehicleSpeed_eX_VehicleSpeed(self, speed);
}

/* --------------------------------------------------------------------------- */
/* RTE Event: /SoftwarePkg/SoftwareComponentPkg/FuelCutAlgo/IB_FuelCutAlgo/OIE_SetAccelerateLevel */

FUNC(void, FuelCutAlgo_CODE) SetAccelerate(CONST(Rte_SelfType_FuelCutAlgo, AUTOMATIC) self,
                                           VAR(uint8, AUTOMATIC) accelerateLevel)
{
   /* ... */
   Rte_IrvWrite_RE_SetAccelerate_eX_AccelerateLevel(self, accelerateLevel);
}

/* --------------------------------------------------------------------------- */
/* RTE Event: /SoftwarePkg/SoftwareComponentPkg/FuelCutAlgo/IB_FuelCutAlgo/OIE_SetBrakeLevel */

FUNC(void, FuelCutAlgo_CODE) SetBrake(CONST(Rte_SelfType_FuelCutAlgo, AUTOMATIC) self,
                                      VAR(uint8, AUTOMATIC) brakeLevel)
{
   /* ... */
   Rte_IrvWrite_RE_SetBrake_eX_BrakeLevel(self, brakeLevel);
}

/* --------------------------------------------------------------------------- */
/* RTE Event: /SoftwarePkg/SoftwareComponentPkg/FuelCutAlgo/IB_FuelCutAlgo/OIE_SetGearLevel */

FUNC(void, FuelCutAlgo_CODE) SetGear(CONST(Rte_SelfType_FuelCutAlgo, AUTOMATIC) self,
                                     VAR(uint8, AUTOMATIC) gearLevel)
{
   /* ... */
   Rte_IrvWrite_RE_SetGear_eX_GearLevel(self, gearLevel);
}

/* --------------------------------------------------------------------------- */
/* RTE Event: /SoftwarePkg/SoftwareComponentPkg/FuelCutAlgo/IB_FuelCutAlgo/TE_SetFuelCutState */

FUNC(void, FuelCutAlgo_CODE) SetFuelCutAction(CONST(Rte_SelfType_FuelCutAlgo, AUTOMATIC) self)
{
   /* ... */
   uint8 actionState;
   uint8 accel = Rte_IrvRead_RE_SetFuelCutAction_eX_AccelerateLevel(self);
   uint8 brake = Rte_IrvRead_RE_SetFuelCutAction_eX_BrakeLevel(self);
   float32 temperature = Rte_IrvRead_RE_SetFuelCutAction_eX_CoolantTemperature(self);
   float32 rpm = Rte_IrvRead_RE_SetFuelCutAction_eX_CrankshaftPosition(self);
   uint8 gear = Rte_IrvRead_RE_SetFuelCutAction_eX_GearLevel(self);
   float32 slope = Rte_IrvRead_RE_SetFuelCutAction_eX_Gyro(self);
   uint8 velocity = Rte_IrvRead_RE_SetFuelCutAction_eX_VehicleSpeed(self);
   
   	   actionState = 0;
   		if(velocity == 0) {
			if(temperature >= 95) {
				actionState = 1;
			} else {
				actionState = 0;
			}
		}
   		else {
			if(gear == 3) {	// Gear N
				if(rpm >= 4700) {
					actionState = 1;
				} else {
					actionState = 0;
				}
			} else{ 	// Gear P, R, D
				if(rpm >= 6800) {
					actionState = 1;
				} else if(rpm >= 2000) {
						if(slope >= 5) {
							if(accel <= 2) {
								actionState = 1;
							}
						} else {
							if(accel == 0) {
								actionState = 1;
							}
						}
					if(slope >= 5) {
						if(accel > 2) {
							actionState = 0;
						}
					} else {
						if(accel!= 0) {
							actionState = 0;
						}
					}
				} else if(rpm < 1500) {
					actionState = 0;
				}
			}
			
			if(brake != 0) {
				actionState = 0;
			}
			
		}
   Rte_IWrite_RE_SetFuelCutAction_PPortFuelCutAction_fuelCutAction( self, actionState );
}

