/** @file     Rte_VehicleSpeedPlausi.c
  *
  * @brief    RTE Sample SWC implementation skeleton file
  *
  * @note     Generated by ETAS GmbH  RTA-RTE v5.4.1  (R4.0 backend version: v7.1.31 (Build 33134))
  *           at Tue Dec 16 20:46:28 2014
  */

#include "Rte_VehicleSpeedPlausi.h"

/* --------------------------------------------------------------------------- */
/* RTE Event: /SoftwarePkg/SoftwareComponentPkg/VehicleSpeedPlausi/IB_VehicleSpeedPlausi/OIE_SetVehicleSpeedRaw */

FUNC(void, VehicleSpeedPlausi_CODE) VehicleSpeedPlausi(CONST(Rte_SelfType_VehicleSpeedPlausi, AUTOMATIC) self,
                                                       VAR(float32, AUTOMATIC) vehicleSpeedRaw)
{
   /* ... */
	Rte_IWrite_RE_VehicleSpeedPlausi_PPortVSPLS_vehicleSpeed_pls( self, vehicleSpeedRaw );
}

