/** @file     Rte_DataHandleType.h
  *
  * @brief    RTE DataElement type definitions
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS GmbH  RTA-RTE v5.4.1  (R4.0 backend version: v7.1.31 (Build 33134))
  *           at Wed Dec 17 17:15:25 2014
  */

#ifndef RTE_DATA_HANDLE_TYPE_H
#define RTE_DATA_HANDLE_TYPE_H

#include "Rte_Type.h"
#include "Rte_Cfg.h"

typedef struct {
   float32 value;
} Rte_DE_float32;

typedef struct {
   uint8 value;
} Rte_DE_uint8;

typedef struct {
   Rte_DE_float32 sbuf0;
   Rte_DE_float32 sbuf1;
   Rte_DE_float32 sbuf2;
   Rte_DE_float32 sbuf3;
} Rte_TDB_OsTask_Plausi;

typedef union {
   Rte_TDB_OsTask_Plausi _OsTask_Plausi;
} Rte_ISA_2;

typedef struct {
   Rte_DE_float32 sbuf0;
   Rte_DE_float32 sbuf1;
   Rte_DE_float32 sbuf2;
   Rte_DE_float32 sbuf3;
} Rte_TDB_OsTask_Algo;

typedef union {
   Rte_TDB_OsTask_Algo _OsTask_Algo;
} Rte_ISA_3;

typedef struct {
   Rte_DE_uint8 sbuf0;
} Rte_TDB_OsTask_AlgoToActuator;

typedef union {
   Rte_TDB_OsTask_AlgoToActuator _OsTask_AlgoToActuator;
} Rte_ISA_4;

typedef struct {
   Rte_DE_uint8 sbuf0;
} Rte_TDB_OsTask_ActuatorToEngine;

typedef union {
   Rte_TDB_OsTask_ActuatorToEngine _OsTask_ActuatorToEngine;
} Rte_ISA_5;

typedef struct {
   Rte_ISA_2 isa_2;
   Rte_ISA_3 isa_3;
   Rte_ISA_4 isa_4;
   Rte_ISA_5 isa_5;
} Rte_ImplicitBufsType;

#endif /* !RTE_DATA_HANDLE_TYPE_H */
