/** @file     Rte_FuelCutAlgo.c
  *
  * @brief    RTE Sample SWC implementation skeleton file
  *
  * @note     Generated by ETAS GmbH  RTA-RTE v5.4.1  (R4.0 backend version: v7.1.31 (Build 33134))
  *           at Tue Dec 16 20:46:28 2014
  */

#include "Rte_FuelCutAlgo.h"

/* --------------------------------------------------------------------------- */
/* RTE Event: /SoftwarePkg/SoftwareComponentPkg/FuelCutAlgo/IB_FuelCutAlgo/DRE_CoolantTempertaturePls */

FUNC(void, FuelCutAlgo_CODE) SetCoolantTemperature(CONST(Rte_SelfType_FuelCutAlgo, AUTOMATIC) self)
{
   /* ... */
}

/* --------------------------------------------------------------------------- */
/* RTE Event: /SoftwarePkg/SoftwareComponentPkg/FuelCutAlgo/IB_FuelCutAlgo/DRE_CrankshaftPositionPls */

FUNC(void, FuelCutAlgo_CODE) SetCrankshaftPosition(CONST(Rte_SelfType_FuelCutAlgo, AUTOMATIC) self)
{
   /* ... */
}

/* --------------------------------------------------------------------------- */
/* RTE Event: /SoftwarePkg/SoftwareComponentPkg/FuelCutAlgo/IB_FuelCutAlgo/DRE_GyroPls */

FUNC(void, FuelCutAlgo_CODE) SetGyro(CONST(Rte_SelfType_FuelCutAlgo, AUTOMATIC) self)
{
   /* ... */
}

/* --------------------------------------------------------------------------- */
/* RTE Event: /SoftwarePkg/SoftwareComponentPkg/FuelCutAlgo/IB_FuelCutAlgo/DRE_VehicleSpeedPls */

FUNC(void, FuelCutAlgo_CODE) SetVehicleSpeed(CONST(Rte_SelfType_FuelCutAlgo, AUTOMATIC) self)
{
   /* ... */
}

/* --------------------------------------------------------------------------- */
/* RTE Event: /SoftwarePkg/SoftwareComponentPkg/FuelCutAlgo/IB_FuelCutAlgo/OIE_SetAccelerateLevel */

FUNC(void, FuelCutAlgo_CODE) SetAccelerate(CONST(Rte_SelfType_FuelCutAlgo, AUTOMATIC) self,
                                           VAR(uint8, AUTOMATIC) accelerateLevel)
{
   /* ... */
}

/* --------------------------------------------------------------------------- */
/* RTE Event: /SoftwarePkg/SoftwareComponentPkg/FuelCutAlgo/IB_FuelCutAlgo/OIE_SetBrakeLevel */

FUNC(void, FuelCutAlgo_CODE) SetBrake(CONST(Rte_SelfType_FuelCutAlgo, AUTOMATIC) self,
                                      VAR(uint8, AUTOMATIC) brakeLevel)
{
   /* ... */
}

/* --------------------------------------------------------------------------- */
/* RTE Event: /SoftwarePkg/SoftwareComponentPkg/FuelCutAlgo/IB_FuelCutAlgo/OIE_SetGearLevel */

FUNC(void, FuelCutAlgo_CODE) SetGear(CONST(Rte_SelfType_FuelCutAlgo, AUTOMATIC) self,
                                     VAR(uint8, AUTOMATIC) gearLevel)
{
   /* ... */
}

/* --------------------------------------------------------------------------- */
/* RTE Event: /SoftwarePkg/SoftwareComponentPkg/FuelCutAlgo/IB_FuelCutAlgo/TE_SetFuelCutState */

FUNC(void, FuelCutAlgo_CODE) SetFuelCutAction(CONST(Rte_SelfType_FuelCutAlgo, AUTOMATIC) self)
{
   /* ... */
}

