/** @file     Rte_FuelCutActuator.c
  *
  * @brief    RTE Sample SWC implementation skeleton file
  *
  * @note     Generated by ETAS GmbH  RTA-RTE v5.4.1  (R4.0 backend version: v7.1.31 (Build 33134))
  *           at Tue Dec 16 20:46:28 2014
  */

#include "Rte_FuelCutActuator.h"

/* --------------------------------------------------------------------------- */
/* RTE Event: /SoftwarePkg/SoftwareComponentPkg/FuelCutActuator/IB_FuelCutActuator/DRE_FuelCutAction */

FUNC(void, FuelCutActuator_CODE) FuelCutActuator(CONST(Rte_SelfType_FuelCutActuator, AUTOMATIC) self)
{
   /* ... */
}

