/** @file     Rte_CoolantTemperaturePlausi.c
  *
  * @brief    RTE Sample SWC implementation skeleton file
  *
  * @note     Generated by ETAS GmbH  RTA-RTE v5.4.1  (R4.0 backend version: v7.1.31 (Build 33134))
  *           at Tue Dec 16 20:46:28 2014
  */

#include "Rte_CoolantTemperaturePlausi.h"

/* --------------------------------------------------------------------------- */
/* RTE Event: /SoftwarePkg/SoftwareComponentPkg/CoolantTemperaturePlausi/IB_CoolantTemperaturePlausi/OIE_SetCoolantTemperatureRaw */

FUNC(void, CoolantTemperaturePlausi_CODE) CoolantTemperaturePlausi(CONST(Rte_SelfType_CoolantTemperaturePlausi, AUTOMATIC) self,
                                                                   VAR(float32, AUTOMATIC) coolantTemperatureRaw)
{
   /* ... */
}

