/** @file     Rte_EngineECU.c
  *
  * @brief    RTE Sample SWC implementation skeleton file
  *
  * @note     Generated by ETAS GmbH  RTA-RTE v5.4.1  (R4.0 backend version: v7.1.31 (Build 33134))
  *           at Tue Dec 16 20:46:28 2014
  */

#include "Rte_EngineECU.h"

/* --------------------------------------------------------------------------- */
/* RTE Event: /SoftwarePkg/SoftwareComponentPkg/EngineECU/IB_EngineECU/OIE_SetFuelCutState */

FUNC(void, EngineECU_CODE) SetFuelCutState(CONST(Rte_SelfType_EngineECU, AUTOMATIC) self,
                                           VAR(uint8, AUTOMATIC) fuelCutState)
{
   /* ... */
}

/* --------------------------------------------------------------------------- */
/* RTE Event: /SoftwarePkg/SoftwareComponentPkg/EngineECU/IB_EngineECU/TE_SendData */

FUNC(void, EngineECU_CODE) SendData(CONST(Rte_SelfType_EngineECU, AUTOMATIC) self)
{
   /* ... */
}

