/** @file     VehicleSpeedPlausi_MemMap.h
  *
  * @brief    RTE Sample SWC MemMap file
  *
  * @note     Generated by ETAS GmbH  RTA-RTE v5.4.1  (R4.0 backend version: v7.1.31 (Build 33134))
  *           at Wed Dec 17 17:15:25 2014
  */

#if defined (START_WITH_IF)
#elif defined(VehicleSpeedPlausi_START_SEC_CODE)
#undef VehicleSpeedPlausi_START_SEC_CODE
#define RTE_START_SEC_APPL_CODE
#elif defined(VehicleSpeedPlausi_STOP_SEC_CODE)
#undef VehicleSpeedPlausi_STOP_SEC_CODE
#define RTE_STOP_SEC_APPL_CODE

#endif /* START_WITH_IF */

#include "MemMap.h"

