/** @file     Rte_Cbk.h
  *
  * @brief    RTE generated COM callbacks
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS GmbH  RTA-RTE v5.4.1  (R4.0 backend version: v7.1.31 (Build 33134))
  *           at Wed Dec 17 18:13:28 2014
  */

#ifndef RTE_CBK_H
#define RTE_CBK_H

/* No COM Callback functions created */
#endif /* !RTE_CBK_H */
