/** @file     Rte_Type.h
  *
  * @brief    RTE type definitions
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS GmbH  RTA-RTE v5.4.1  (R4.0 backend version: v7.1.31 (Build 33134))
  *           at Wed Dec 17 18:13:28 2014
  */

#ifndef RTE_TYPE_H
#define RTE_TYPE_H

#include "Rte.h"
#include "Rte_Cfg.h"

/*******************************************************
 ***
 *** Forward Declarations
 ***
 *******************************************************/

struct Rte_CDS_CoolantTemperaturePlausi;
struct Rte_CDS_CrankshaftPositionPlausi;
struct Rte_CDS_EngineECU;
struct Rte_CDS_FuelCutActuator;
struct Rte_CDS_FuelCutAlgo;
struct Rte_CDS_GyroPlausi;
struct Rte_CDS_VehicleSpeedPlausi;

/*******************************************************
 ***
 *** Types
 ***
 *******************************************************/

typedef unsigned char uint8;

typedef uint8 boolean;

typedef float float32;

typedef double float64;

typedef short sint16;

typedef signed int sint16_least;

typedef int sint32;

typedef signed int sint32_least;

typedef signed char sint8;

typedef signed int sint8_least;

typedef unsigned int uint16_least;

typedef unsigned int uint32;

typedef unsigned int uint32_least;

typedef unsigned int uint8_least;

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_EngineECU_CS_IF_ACCELERATE_SetAccelerateLevel) (VAR(uint8, AUTOMATIC) accelerateLevel);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_EngineECU_CS_IF_BRAKE_SetBrakeLevel) (VAR(uint8, AUTOMATIC) brakeLevel);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_EngineECU_CS_IF_CP_RAW_SetCrankshaftPositionRaw) (VAR(float32, AUTOMATIC) crankshaftPositionRaw);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_EngineECU_CS_IF_CT_RAW_SetCoolantTemperatureRaw) (VAR(float32, AUTOMATIC) coolantTemperatureRaw);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_EngineECU_CS_IF_GEAR_SetGearLevel) (VAR(uint8, AUTOMATIC) gearLevel);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_EngineECU_CS_IF_GYRO_RAW_SetGyroRaw) (VAR(float32, AUTOMATIC) gyroRaw);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_EngineECU_CS_IF_VS_RAW_SetVehicleSpeedRaw) (VAR(float32, AUTOMATIC) vehicleSpeedRaw);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_FuelCutActuator_CS_IF_SET_FUELCUT_STATE_SetFuelCutState) (VAR(uint8, AUTOMATIC) fuelCutState);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_ImplWriteFP_CoolantTemperaturePlausi_SR_IF_CT_PLS_coolantTemperature_pls) (VAR(float32, AUTOMATIC) data);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_ImplWriteFP_CrankshaftPositionPlausi_SR_IF_CP_PLS_crankshaftPosition_pls) (VAR(float32, AUTOMATIC) data);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_ImplWriteFP_FuelCutAlgo_SR_IF_FUELCUT_ACTION_fuelCutAction) (VAR(uint8, AUTOMATIC) data);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_ImplWriteFP_GyroPlausi_SR_IF_GYRO_PLS_gyro_pls) (VAR(float32, AUTOMATIC) data);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_ImplWriteFP_VehicleSpeedPlausi_SR_IF_VS_PLS_vehicleSpeed_pls) (VAR(float32, AUTOMATIC) data);

typedef P2FUNC(VAR(uint8, AUTOMATIC), RTE_CODE, Rte_IrvReadFP_FuelCutAlgo_RE_SetFuelCutAction_eX_AccelerateLevel) (void);

typedef P2FUNC(VAR(uint8, AUTOMATIC), RTE_CODE, Rte_IrvReadFP_FuelCutAlgo_RE_SetFuelCutAction_eX_BrakeLevel) (void);

typedef P2FUNC(VAR(float32, AUTOMATIC), RTE_CODE, Rte_IrvReadFP_FuelCutAlgo_RE_SetFuelCutAction_eX_CoolantTemperature) (void);

typedef P2FUNC(VAR(float32, AUTOMATIC), RTE_CODE, Rte_IrvReadFP_FuelCutAlgo_RE_SetFuelCutAction_eX_CrankshaftPosition) (void);

typedef P2FUNC(VAR(uint8, AUTOMATIC), RTE_CODE, Rte_IrvReadFP_FuelCutAlgo_RE_SetFuelCutAction_eX_GearLevel) (void);

typedef P2FUNC(VAR(float32, AUTOMATIC), RTE_CODE, Rte_IrvReadFP_FuelCutAlgo_RE_SetFuelCutAction_eX_Gyro) (void);

typedef P2FUNC(VAR(float32, AUTOMATIC), RTE_CODE, Rte_IrvReadFP_FuelCutAlgo_RE_SetFuelCutAction_eX_VehicleSpeed) (void);

typedef P2FUNC(void, RTE_CODE, Rte_IrvWriteFP_EngineECU_RE_SetFuelCutState_eX_FuelCutState) (VAR(uint8, AUTOMATIC) data);

typedef P2FUNC(void, RTE_CODE, Rte_IrvWriteFP_FuelCutAlgo_RE_SetAccelerate_eX_AccelerateLevel) (VAR(uint8, AUTOMATIC) data);

typedef P2FUNC(void, RTE_CODE, Rte_IrvWriteFP_FuelCutAlgo_RE_SetBrake_eX_BrakeLevel) (VAR(uint8, AUTOMATIC) data);

typedef P2FUNC(void, RTE_CODE, Rte_IrvWriteFP_FuelCutAlgo_RE_SetCoolantTemperature_eX_CoolantTemperature) (VAR(float32, AUTOMATIC) data);

typedef P2FUNC(void, RTE_CODE, Rte_IrvWriteFP_FuelCutAlgo_RE_SetCrankshaftPosition_eX_CrankshaftPosition) (VAR(float32, AUTOMATIC) data);

typedef P2FUNC(void, RTE_CODE, Rte_IrvWriteFP_FuelCutAlgo_RE_SetGear_eX_GearLevel) (VAR(uint8, AUTOMATIC) data);

typedef P2FUNC(void, RTE_CODE, Rte_IrvWriteFP_FuelCutAlgo_RE_SetGyro_eX_Gyro) (VAR(float32, AUTOMATIC) data);

typedef P2FUNC(void, RTE_CODE, Rte_IrvWriteFP_FuelCutAlgo_RE_SetVehicleSpeed_eX_VehicleSpeed) (VAR(float32, AUTOMATIC) data);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_ResultFP_EngineECU_CS_IF_ACCELERATE_SetAccelerateLevel) (void);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_ResultFP_EngineECU_CS_IF_BRAKE_SetBrakeLevel) (void);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_ResultFP_EngineECU_CS_IF_CP_RAW_SetCrankshaftPositionRaw) (void);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_ResultFP_EngineECU_CS_IF_CT_RAW_SetCoolantTemperatureRaw) (void);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_ResultFP_EngineECU_CS_IF_GEAR_SetGearLevel) (void);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_ResultFP_EngineECU_CS_IF_GYRO_RAW_SetGyroRaw) (void);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_ResultFP_EngineECU_CS_IF_VS_RAW_SetVehicleSpeedRaw) (void);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_ResultFP_FuelCutActuator_CS_IF_SET_FUELCUT_STATE_SetFuelCutState) (void);

typedef CONSTP2CONST(struct Rte_CDS_CoolantTemperaturePlausi,AUTOMATIC,RTE_CONST) Rte_SelfType_CoolantTemperaturePlausi;

typedef CONSTP2CONST(struct Rte_CDS_CrankshaftPositionPlausi,AUTOMATIC,RTE_CONST) Rte_SelfType_CrankshaftPositionPlausi;

typedef CONSTP2CONST(struct Rte_CDS_EngineECU,AUTOMATIC,RTE_CONST) Rte_SelfType_EngineECU;

typedef CONSTP2CONST(struct Rte_CDS_FuelCutActuator,AUTOMATIC,RTE_CONST) Rte_SelfType_FuelCutActuator;

typedef CONSTP2CONST(struct Rte_CDS_FuelCutAlgo,AUTOMATIC,RTE_CONST) Rte_SelfType_FuelCutAlgo;

typedef CONSTP2CONST(struct Rte_CDS_GyroPlausi,AUTOMATIC,RTE_CONST) Rte_SelfType_GyroPlausi;

typedef CONSTP2CONST(struct Rte_CDS_VehicleSpeedPlausi,AUTOMATIC,RTE_CONST) Rte_SelfType_VehicleSpeedPlausi;

typedef struct {
   float32         coolantTemperatureRaw;
   Rte_QCmnRefType clientQueue;
} Rte_SwComponentPrototype_CoolantTemperaturePlausi_PPortCTRAW_SetCoolantTemperatureRaw_QEType;

typedef struct {
   uint8 dummy;
} Rte_SwComponentPrototype_CoolantTemperaturePlausi_PPortCTRAW_SetCoolantTemperatureRaw_RtnQEType;

typedef struct {
   float32         crankshaftPositionRaw;
   Rte_QCmnRefType clientQueue;
} Rte_SwComponentPrototype_CrankshaftPositionPlausi_PPortCPRAW_SetCrankshaftPositionRaw_QEType;

typedef struct {
   uint8 dummy;
} Rte_SwComponentPrototype_CrankshaftPositionPlausi_PPortCPRAW_SetCrankshaftPositionRaw_RtnQEType;

typedef struct {
   uint8           fuelCutState;
   Rte_QCmnRefType clientQueue;
} Rte_SwComponentPrototype_EngineECU_PPortSetFuelCutState_SetFuelCutState_QEType;

typedef struct {
   uint8 dummy;
} Rte_SwComponentPrototype_EngineECU_PPortSetFuelCutState_SetFuelCutState_RtnQEType;

typedef struct {
   uint8           accelerateLevel;
   Rte_QCmnRefType clientQueue;
} Rte_SwComponentPrototype_FuelCutAlgo_PPortAccelerate_SetAccelerateLevel_QEType;

typedef struct {
   uint8 dummy;
} Rte_SwComponentPrototype_FuelCutAlgo_PPortAccelerate_SetAccelerateLevel_RtnQEType;

typedef struct {
   uint8           brakeLevel;
   Rte_QCmnRefType clientQueue;
} Rte_SwComponentPrototype_FuelCutAlgo_PPortBrake_SetBrakeLevel_QEType;

typedef struct {
   uint8 dummy;
} Rte_SwComponentPrototype_FuelCutAlgo_PPortBrake_SetBrakeLevel_RtnQEType;

typedef struct {
   uint8           gearLevel;
   Rte_QCmnRefType clientQueue;
} Rte_SwComponentPrototype_FuelCutAlgo_PPortGear_SetGearLevel_QEType;

typedef struct {
   uint8 dummy;
} Rte_SwComponentPrototype_FuelCutAlgo_PPortGear_SetGearLevel_RtnQEType;

typedef struct {
   float32         gyroRaw;
   Rte_QCmnRefType clientQueue;
} Rte_SwComponentPrototype_GyroPlausi_PPortGyroRAW_SetGyroRaw_QEType;

typedef struct {
   uint8 dummy;
} Rte_SwComponentPrototype_GyroPlausi_PPortGyroRAW_SetGyroRaw_RtnQEType;

typedef struct {
   float32         vehicleSpeedRaw;
   Rte_QCmnRefType clientQueue;
} Rte_SwComponentPrototype_VehicleSpeedPlausi_PPortVSRAW_SetVehicleSpeedRaw_QEType;

typedef struct {
   uint8 dummy;
} Rte_SwComponentPrototype_VehicleSpeedPlausi_PPortVSRAW_SetVehicleSpeedRaw_RtnQEType;

#endif /* !RTE_TYPE_H */
