/** @file     Rte_Cfg.h
  *
  * @brief    RTE Configuration file
  *
  * @note     Generated by ETAS GmbH  RTA-RTE v5.4.1  (R4.0 backend version: v7.1.31 (Build 33134))
  *           at Wed Dec 17 18:21:49 2014
  */

#ifndef RTE_CFG_H
#define RTE_CFG_H

#include <Std_Types.h>

/* BEGIN: VFB tracing definitions */
#ifndef RTE_VFB_TRACE
#define RTE_VFB_TRACE                            (0)
#endif /*RTE_VFB_TRACE*/
/* END: VFB tracing definitions */

#endif /* !RTE_CFG_H */
